version: "3"
services:
  backend:
    build:
      context: .
    container_name: "ems"
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
  mysql:
    image: mysql
    container_name: "mysql"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ems_db:/var/lib/mysql
      - ./DATABASE_FILE/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "Nic@123"
      MYSQL_DATABASE: "ems"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "Nic@123"
  phpmyadmin:
    image: phpmyadmin
    container_name: "phpmyadmin"
    links:
      - mysql:mysql
    ports:
      - 8000:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
volumes:
  ems_db: