apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: QWRtaW5AMTIzNA==  # base64 encoded value
  MYSQL_USER: YWRtaW4=  # base64 encoded value (To make base64 password Example: echo -n 'my-password' | base64)
  MYSQL_PASSWORD: QWRtaW5AMTIzNA== # base64 encoded value