 apiVersion: v1
 kind: Secret
 metadata:
   name: mysql-secret
 type: Opaque
 data:
   username: dXNlcm5hbWU=  # base64 encoded value of "username"
   password: cGFzc3dvcmQ=  # base64 encoded value of "password" To make base64 password Example: echo -n 'my-password' | base64